# Generated by Django 6.0.7 on 2026-10-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pen', 'Pending'), ('Acc', 'Accepted'), ('Cancel', 'Cancelled'), ('Out', 'Checked_Out')], max_length=100),
        ),
    ]
